"""testDB table

Revision ID: f38da79eb541
Revises: 4e874a3554be
Create Date: 2022-07-31 20:58:53.949046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38da79eb541'
down_revision = '4e874a3554be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_session', 'main_node_count')
    op.add_column('user_commitment', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user_commitment', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('user_commitment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_commitment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_commitment', type_='foreignkey')
    op.drop_column('user_commitment', 'user_id')
    op.drop_column('user_commitment', 'last_updated')
    op.drop_column('user_commitment', 'date_created')
    op.add_column('model_session', sa.Column('main_node_count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
