"""testDB table

Revision ID: fefb05158e6c
Revises: ece6112177a0
Create Date: 2022-07-31 19:46:23.267900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefb05158e6c'
down_revision = 'ece6112177a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_session', sa.Column('a05_count', sa.Integer(), nullable=True))
    op.add_column('model_session', sa.Column('a11_count', sa.Integer(), nullable=True))
    op.add_column('model_session', sa.Column('b05_count', sa.Integer(), nullable=True))
    op.add_column('model_session', sa.Column('b09_count', sa.Integer(), nullable=True))
    op.add_column('model_session', sa.Column('e04_count', sa.Integer(), nullable=True))
    op.drop_column('model_session', 'b04_count')
    op.drop_column('model_session', 'a04_count')
    op.drop_column('model_session', 'b08_count')
    op.drop_column('model_session', 'a08_count')
    op.drop_column('model_session', 'e03_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_session', sa.Column('e03_count', sa.INTEGER(), nullable=True))
    op.add_column('model_session', sa.Column('a08_count', sa.INTEGER(), nullable=True))
    op.add_column('model_session', sa.Column('b08_count', sa.INTEGER(), nullable=True))
    op.add_column('model_session', sa.Column('a04_count', sa.INTEGER(), nullable=True))
    op.add_column('model_session', sa.Column('b04_count', sa.INTEGER(), nullable=True))
    op.drop_column('model_session', 'e04_count')
    op.drop_column('model_session', 'b09_count')
    op.drop_column('model_session', 'b05_count')
    op.drop_column('model_session', 'a11_count')
    op.drop_column('model_session', 'a05_count')
    # ### end Alembic commands ###
